/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RL78_wifi_sql                          */
/*      FILE         :  interrupt_handlers.c                   */
/*      DESCRIPTION  :  Interrupt Handler                      */
/*      CPU SERIES   :  RL78 - G12                             */
/*      CPU TYPE     :  R5F1026A                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                            
                                                                                   
/************************************************************************/
/* Header file generated from device file:                              */
/*    DR5F1026A.DVF                                                     */
/*    V1.12 (2012/04/03)                                                */
/*    Copyright(C) 2012 Renesas                                         */
/* Tool Version: 3.5.3                                                  */
/* Date Generated: 2016/02/17                                           */
/************************************************************************/
#include "interrupt_handlers.h"

/*
 * INT_WDTI (0x4)
 */
void INT_WDTI (void) { }

/*
 * INT_LVI (0x6)
 */
void INT_LVI (void) { }

/*
 * INT_P0 (0x8)
 */
void INT_P0 (void) { }

/*
 * INT_P1 (0xA)
 */
void INT_P1 (void) { }

/*
 * INT_P2 (0xC)
 */
void INT_P2 (void) { }

/*
 * INT_P3 (0xE)
 */
void INT_P3 (void) { }

/*
 * INT_DMA0 (0x10)
 */
void INT_DMA0 (void) { }

/*
 * INT_DMA1 (0x12)
 */
void INT_DMA1 (void) { }

/*
 * INT_CSI00/INT_IIC00/INT_ST0 (0x14)
 */
void INT_ST0 (void) { }
//void INT_CSI00 (void) { }
//void INT_IIC00 (void) { }

/*
 * INT_CSI01/INT_IIC01/INT_SR0 (0x16)
 */
void INT_SR0 (void) { }
//void INT_CSI01 (void) { }
//void INT_IIC01 (void) { }

/*
 * INT_SRE0 (0x18)
 */
void INT_SRE0 (void) { }

/*
 * INT_TM01H (0x1A)
 */
void INT_TM01H (void) { }

/*
 * INT_TM03H (0x1C)
 */
void INT_TM03H (void) { }

/*
 * INT_IICA0 (0x1E)
 */
void INT_IICA0 (void) { }

/*
 * INT_TM00 (0x20)
 */
void INT_TM00 (void) { }

/*
 * INT_TM01 (0x22)
 */
void INT_TM01 (void) { }

/*
 * INT_TM02 (0x24)
 */
void INT_TM02 (void) { }

/*
 * INT_TM03 (0x26)
 */
void INT_TM03 (void) { }

/*
 * INT_AD (0x28)
 */
void INT_AD (void) { }

/*
 * INT_IT (0x2A)
 */
void INT_IT (void) { }

/*
 * INT_KR (0x2C)
 */
void INT_KR (void) { }

/*
 * INT_MD (0x2E)
 */
void INT_MD (void) { }

/*
 * INT_FL (0x30)
 */
void INT_FL (void) { }

/*
 * INT_BRK_I (0x7E)
 */
void INT_BRK_I (void) { }
